name: Deploy Static Site to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Add EC2 host key
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -H ${{ secrets.EC2_INSTANCE_IP }} >> ~/.ssh/known_hosts

    - name: Deploy to EC2
      run: |
        echo "$DEPLOY_KEY" > key.pem
        chmod 600 key.pem
        rsync -avz -e "ssh -i key.pem" ./ ec2-user@${{ secrets.EC2_INSTANCE_IP }}:/var/www/html/
      env:
        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
        EC2_INSTANCE_IP: ${{ secrets.EC2_INSTANCE_IP }}
