name: Deploy Static Site to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to EC2
      run: |
        ssh -i "$DEPLOY_KEY" ec2-user@$EC2_INSTANCE_IP << 'EOF'
          # Ensure the target directory exists
          mkdir -p /var/www/html

          # Navigate to the target directory
          cd /var/www/html

          # Remove old files if any
          rm -rf *

          # Pull the latest code from GitHub repository
          git pull origin main || git clone https://github.com/yourusername/your-repo.git .

          # Set permissions if needed
          sudo chown -R ec2-user:ec2-user /var/www/html
        EOF
      env:
        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
        EC2_INSTANCE_IP: ${{ secrets.EC2_INSTANCE_IP }}
