name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Deploy to EC2
      run: |
        ssh -i "$DEPLOY_KEY" ec2-user@$EC2_INSTANCE_IP << 'EOF'
          cd /var/www/html
          git pull origin main
          # Restart your application if needed
          # For example: sudo systemctl restart my-app.service
        EOF
      env:
        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
        EC2_INSTANCE_IP: ${{ secrets.EC2_INSTANCE_IP }}
