name: Deploy Static Site to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Add EC2 host key
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -H ${{ secrets.EC2_INSTANCE_IP }} >> ~/.ssh/known_hosts

    - name: Deploy to EC2
      run: |
        rsync -avz -e "ssh -i ${{ secrets.DEPLOY_KEY }}" ./ ec2-user@$EC2_INSTANCE_IP:/var/www/html
      env:
        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
        EC2_INSTANCE_IP: ${{ secrets.EC2_INSTANCE_IP }}
